fotoalbum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('post.urls')),
    path('admin/', admin.site.urls),
    # path('/')
]

post/urls.py
from django.conf.urls import url

from . import views

app_name = 'post'

urlpatterns = [
    url(r'^(?P<page_number>\d+)/$', views.main, name='main'),
    url(r'^login/', views.login_func, name='login_func'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^$', views.main, name='main'),
    # url(r'^post_image_page/', views.post_image_page, name='post_image_page'),
    # url(r'^post_inst_image_page/', views.post_inst_image_page, name='post_inst_image_page'),
    # url(r'^login/', views.login_func, name='login_func'),
    # url(r'^logout/', views.logout, name='logout'),
    # url(r'^signup/$', views.signup, name='signup'),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    # url(r'^$', views.main, name='main'),
]

post/models.py
from django.db import models

# Create your models here.

from datetime import datetime


class Post(models.Model):

	post_title = models.CharField(max_length=200)
	post_description = models.CharField(max_length=200)
	post_date = models.DateTimeField(default=datetime.now)
	post_image_url = models.CharField(default='<empty>', max_length=400)
	post_image = models.ImageField(upload_to='static')
	# post_video_url = models.CharField(default='', max_length=400)
	# post_video = models.ImageField(upload_to='static')

post/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.admin import widgets
from .models import Post
from datetime import datetime


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    birthday = forms.DateField(initial='month/day/year')
    country = forms.CharField()
    city = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'birthday',
        		  'country', 'city')

post/views.py
# Create your views here.
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from datetime import datetime
# import urllib2
# import urllib
# import json
# import os

from django.shortcuts import render
from .models import Post
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.contrib import auth
from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.template.context_processors import csrf
from django.core.paginator import Paginator
# from .forms import PostForm, PostInstagramForm

def main(request, page_number=1):
	print('MAIN')
	context = {}
	username = request.user.username
	# user_like_list = []
	posts_list = Post.objects.all().order_by('-post_date')
	# for post in posts_list:
	# 	if username in post.return_list_of_user():
	# 		user_like_list.append(post.id)
	current_page = Paginator(posts_list, 2)
	if username:
		context['username'] = username		
	context['list_of_posts'] = current_page.page(page_number)
	# context['user_like_list'] = user_like_list
	return render(request, 'post/main.html', context)


def signup(request):
	if request.method == 'POST':
		print('request.POST : ', request.POST)
		form = SignupForm(request.POST)
		print('form : ', form)
		print('form.is_valid() : ', form.is_valid())
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			print('!!!!!!!!!!!!!!!!!!!!!!!!!!!', urlsafe_base64_encode(force_bytes(user.pk)).decode())
			print('!!!!!!!!!!!!!!!!!!!!!!!!!!!', urlsafe_base64_encode(force_bytes(user.pk)))
			message = render_to_string('post/acc_active_email.html', {
				'user':user, 
				'domain':current_site.domain,
				'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
				'token': account_activation_token.make_token(user),
			})
			mail_subject = 'Activate your blog account.'
			to_email = form.cleaned_data.get('email')
			email = EmailMessage(mail_subject, message, to=[to_email])
			email.send()
			return HttpResponse('Please confirm your email address to complete the registration')
	else:
		form = SignupForm()
	return render(request, 'post/signup.html', {'form': form})


def activate(request, uidb64, token):
	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
	except(TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None
	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.save()
		login(request, user)
		# return redirect('home')
		# return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
		return redirect('/')
	else:
		return HttpResponse('Activation link is invalid!')


def login_func(request):
	args = {}
	args.update(csrf(request))
	if request.POST:
		username = request.POST.get('username', '')
		password = request.POST.get('password', '')
		user = auth.authenticate(username=username, password=password)
		if user is not None:
			auth.login(request, user)
			return redirect('/')
		else:
			args['login_error'] = 'Log in error'
			return render_to_response('post/login.html', args)
	else:
		return render(request, 'post/login.html', args)


def logout(request):
	auth.logout(request)
	return redirect('/1/')

post/templates/post/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'post:activate' uidb64=uid token=token %}
{% endautoescape %}

post/templates/post/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Post_page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
    <div class="thumbnails">
        <div class="well inline-headers">
            <form action="/login/" method="post">
                {% csrf_token %}
                <label for="username">User name</label>
                <input type="text" name="username" id="username">
                <label for="password">Password</label>
                <input type="password" name="password" id="password">
                {% if login_error %}
                    <label class="error">{{ login_error }}</label>
                {% endif %}
                <input class="button" type="submit" value="Submit">
            <div><a href="/signup/">Register</a></div>
            </form>
        </div>
    </div>
</html>

post/templates/post/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Main Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

<ul class="thumbnails">
		<div class="well inline-headers">
		{% if username %}
				<h4>Account: {{username}}</h4>
				<h5><a href="/logout/">Logout</a></h5>
		{% else %}
			<h5><a href="/login/">Login</a></h5>
			<h5><a href="/signup/">Register</a></h5>
		{% endif %}
		</div>
		{% if username %}
		<div class="well inline-headers">
				<h5><a href="/post_image_page/">Post image</a></h5>
				<h5><a href="/post_inst_image_page/">Post Instagram image</a></h5>
		</div>
		{% endif %}
		<hr>
		<h1>LIST OF POSTS</h1>
		<hr>
		{% for post in list_of_posts %}
			<li class='span3'>
				<figure>
            		<!-- <img src="https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Oxalis_tetraphylla_flower.jpg/640px-Oxalis_tetraphylla_flower.jpg" width='300px' height="200px" alt="3 column placeholder" /> -->
                	<h3>{{ post.post_title }}</h3>
            		<img src={% static post.post_image %} width='300px' height="200px" alt="3 column placeholder" />
            		<figcaption>
            			<!-- {% if username %}
							<h4><a href="/addlike/{{ post.id }}/">Like{% if post.id in user_like_list %} <img src='https://openclipart.org/image/2400px/svg_to_png/145537/Simple-Red-Heart.png' width='15px' height="15px" /> {% else %} <img src='https://img2.embroiderydesigns.com/StockDesign/XLarge/Grand_Slam_Designs/love27.jpg' width='15px' height="15px" /> {% endif %} </a>{{ post.post_likes }}</h4>
						{% else %}
							<h4>Likes: {{ post.post_likes }}</h4>
						{% endif %} -->
                		<h3>{{ post.post_description|safe }}</h3>
                		<h3>{{ post.post_date }}</h3>
                		<h4>Published by: {{ username }}</h4>
            		</figcaption>
        		</figure>
			</li><br>
			<hr>
		{% endfor %}
		<div margin-left='100px'>
		        <div class="row">
		            <ul class="pagination">
		                {% if list_of_posts.has_previous %}
		                    <li class="arrow"><a href="/{{ list_of_posts.previous_page_number }}/">&laquo;</a></li>
		                {% else %}
		                    <li class="arrow unavailable"><a href="">&laquo;</a></li>
		                {% endif %}
		                {% for page in list_of_posts.paginator.page_range %}
		                    {% if page == list_of_posts.number %}
		                        <li class="current"><a href="/{{ page }}/">{{ page }}</a></li>
		                    {% else %}
		                        <li><a href="/{{ page }}/">{{ page }}</a></li>
		                    {% endif %}
		                {% endfor %}
		                {% if list_of_posts.has_next %}
		                    <li class="arrow"><a href="/{{ list_of_posts.next_page_number }}/">&raquo;</a></li>
		                {% else %}
		                    <li class="arrow unavailable"><a href="">&raquo;</a></li>
		                {% endif %}
		            </ul>
		        </div>
    		</div>
</ul>

</body>
</html>

post/templates/post/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Post_page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
  <div class="thumbnails">
    <div class="well inline-headers">
      <h2>Sign up</h2>
      <form method="post">
        {% csrf_token %}
          {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="display: none">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
          {% endfor %}

        <button type="submit">Sign up</button>
      </form>
    </div>
  </div>
</html>